name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST: "ssh://${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}"
      COMPOSE_PROJECT_NAME: "${{ vars.DOCKER_PROJECT }}"

      # Docker compose's args
      GRAFANA_HOST: ${{ vars.GRAFANA_HOST }}
      GRAFANA_SERVER_ROOT_URL: ${{ vars.GRAFANA_SERVER_ROOT_URL }}

      PROMETHEUS_HOST: ${{ vars.PROMETHEUS_HOST }}

      PUBLIC_PORT: ${{ vars.PUBLIC_PORT }}
      DASHBOARD_HOST: ${{ vars.DASHBOARD_HOST }}
      DASHBOARD_AUTH: ${{ secrets.DASHBOARD_AUTH }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known_hosts
        run: 'ssh-keyscan ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts'

      - name: Compile on the server
        run: 'docker compose build'

      - name: Deploy to server
        run: 'docker compose up -d --remove-orphans'
